
// AUTH
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER ='LOGOUT_USER';
 
// GENERAL
export const START_LOADING = 'START_LOADING';
export const ERRORS = 'ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// USERS
export const GET_USERS = 'GET_USERS';
export const NEW_USER = 'NEW_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_INSTRUCTORS = 'GET_INSTRUCTORS';
export const STUDENT_DATA = 'STUDENT_DATA';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const USERS_START_LOADING = 'USERS_START_LOADING';
export const USERS_ERRORS = 'USERS_ERRORS';


// COURSES
export const GET_COURSES = 'GET_COURSES';
export const NEW_COURSE = 'NEW_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const COURSES_START_LOADING = 'COURSES_START_LOADING';
export const COURSES_ERRORS = 'COURSES_ERRORS';

// Topics
export const ADD_TOPIC = 'ADD_TOPIC';
export const DELETE_TOPIC = 'DELETE_TOPIC';
export const GET_TOPICS = 'GET_TOPICS';


export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_COMMENTS = 'GET_COMMENTS';

//degrees
export const GET_DEGREES = 'GET_DEGREES';
export const NEW_DEGREE = 'NEW_DEGREE';
export const DELETE_DEGREE = 'DELETE_DEGREE';
export const GET_DEGREE_COURSES = 'GET_DEGREE_COURSES';
export const ADD_DEGREE_COURSES = 'ADD_DEGREE_COURSES';
export const DELETE_DEGREE_COURSES = 'DELETE_DEGREE_COURSES';
export const DEGREES_START_LOADING = 'DEGREES_START_LOADING';
export const DEGREES_ERRORS = 'DEGREES_ERRORS';
